### ISSUE TITLE
Device not found

### ISSUE THREAD

**Issue by captaindannduece** [baldapps/airtaskdesktop#1]
Can't find android AirTask app on same lan even though I configured the desktop to use the same name as the 'device name" set in the app. Also, how can I run the commandline functions in headless mode?

**Comment by baldapps** [comment]
About command line: you find the instructions in the readme file. AirTask can be invoked from command line using the following arguments:

-d DEVICE: To specify a device as destination. If not specified, the default one is used
(if any)
-f FILE: To transfer a file using its path
-m MESSAGE: To transfer a message
-clip: To copy the pc clipboard to a device selected with -d or the default one

About the network problem: did you open all the needed ports on your desktop? If not, the connection is blocked by your firewall. It's the only reason why it work PC->Phone but it doesn't work Phone->PC. In addition you need to add the PC device in your phone with the same name and the IP address. If you use DHCP my suggestions is to use a static ip for your pc or to use address reservation in the configurations of your router.

**Comment by amokkatgithub** [comment]
Caption is same for my problem, but not contents.
I have 2 devices configured, but with command line I can send message only to default configured.
When I specify device name via -d parameter, I only get "Device not found". Does not matter if I specify correct one from list, default or not - same result. Have no spaces nor special chars in names. Tried quoting with single and double - all the same.
Using Windows.

**Comment by baldapps** [comment]
I think I found the bug about the command line name parameters. I try to fix it asap.

**Comment by baldapps** [comment]
Fixed in 1.2.2 version

**Comment by captaindannduece** [comment]
Still not fixed for me. Opened ports from readme on firewall. Still can't find device.

**Comment by baldapps** [comment]
Do you have problem from phone to pc, pc to phone or both? Have you configured the devices with IP addresses both on pc and phone?

**Comment by captaindannduece** [comment]
Both, phone is fully configured. How do you configure the desktop besides allowing ports?

**Comment by baldapps** [comment]
Ok. I think your problems are:
1) To send messages to your phone you need to configure the app. In order to configure to app you need to start the app with a graphic environment. Use the "options" menu in the toolbar. See attached image. If you don't configure the desktop app, it won't work because it doesn't know the ip addresses.
2) If you don't start the desktop app from a graphic environment the app won't listen to phone because it **isn't** a background demon server (at least now).
![aaa](https://cloud.githubusercontent.com/assets/14140069/19396873/68dd032e-9245-11e6-8ab7-ea9305ff0a90.png)

**Comment by captaindannduece** [comment]
Can you develop it into one? Otherwise I'm stuck sending telnet messages to my phone.

**Comment by baldapps** [comment]
Not at the moment, but I can add it to the TODO list.

**Comment by captaindannduece** [comment]
Thanks. Will keep following.
